jobportal/accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_view

app_name = 'accounts'

# urlpatterns = [    
#     path('register/', views.registerEmployee, name='register'),
#     path('register_employer/', views.registerEmployer, name='register_employer'),
#     path('profile/', views.employee_edit_profile, name='employee_edit_profile'),
#     path('profile_employer/', views.employer_edit_profile, name='employer_edit_profile'),
#     path('change-password/', views.employee_edit_profile, name='password_change'),
#     path('login/', views.login_user, name='login'),
#     # path('login_employer/', views.login_employer, name='login_employer'),
#     path('logout/', views.logout_view, name='logout'),  
   
# ]

urlpatterns = [    
    # Public routes
    path('register/', views.registerEmployee, name='register'),
    path('register/employer/', views.registerEmployer, name='register_employer'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # Employee-only section
    path('profile/', views.employee_edit_profile, name='employee_edit_profile'),
    path('profile/change-password/', views.employee_edit_profile, name='password_change'),

    # Employer-only section (matches /company/ pattern)
    path('company/profile/', views.employer_edit_profile, name='employer_edit_profile'),
]

jobportal/company_panel/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_view



app_name = 'company_panel'

urlpatterns = [    

    # Employer-only section (matches /company/ pattern)
    path('company/panel/', views.company_panel, name='company_panel'),
    path('company/panel/edit/<int:pk>/', views.edit_job_offer, name='edit_job_offer'),
    path('company/panel/create/', views.create_job_offer, name='create_job_offer'),

]

jobportal/core/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_view



urlpatterns = [
    path('', views.index, name='index'),    
   
]

jobportal/jobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('external_api.urls')),
    path('', include('accounts.urls')), 
    path('', include('company_panel.urls')),
    path('', include('applications.urls')),
    path('', include('jobboard.urls'))

] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / "static")

jobportal/core/models.py
from django.db import models

# Create your models here.

jobportal/core/views.py
from django.shortcuts import render
import requests
from django.conf import settings 
from external_api.views import get_reed_jobs 
from accounts.models import EmployeeProfile, EmployerProfile
import json

# Create your views here.

def index(request): 
    user = request.user
    
    # Initialize profile as None
    profile = None 
    
    print(user)

    if user.is_authenticated:
        try:
            if hasattr(user, 'role') and user.role == "employer":  
                profile = EmployerProfile.objects.get(user_id=user.id)
            else:  
                profile = EmployeeProfile.objects.get(user_id=user.id)
        except (EmployerProfile.DoesNotExist, EmployeeProfile.DoesNotExist):
            profile = None  # Handle missing profile gracefully
    else:
        # Optionally redirect to login page
        # return redirect('login')
        pass

    jobs_data = get_reed_jobs(query='django developer')

    if jobs_data:
        jobs = jobs_data.get('results', [])
    else:
        jobs = []

    return render(request, 'core/index.html', { 'jobs': jobs, 'profile': profile })

jobportal/core/templates/core/base.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>JobEntry - Job Portal Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'core/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'core/css/style.css' %}?v={{ now|date:'U' }}" rel="stylesheet">

</head>

<body>
    <div class="container-fluid bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white shadow sticky-top p-0">
            <div class="container-fluid">
                <a href="index.html" class="navbar-brand text-primary px-4 py-2">
                    <a href="/">
                        <h1 class="m-0">JobEntry</h1>
                    </a>                    
                </a>
                <button class="navbar-toggler me-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ms-auto px-3">
                        <li class="nav-item">
                            <a class="nav-link active" href="index.html">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="about.html">About</a>
                        </li>
                        {% if user.is_authenticated and user.role == 'employer' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company_panel:company_panel' %}">Company Panel</a>
                        </li>
                        {% endif %}
        
                        <!-- Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="createAccountDropdown" role="button" data-bs-toggle="dropdown">
                                Create Account
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Job Seeker</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:register_employer' %}">Company</a></li>
                            </ul>
                        </li>
        
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="#" class="nav-link" onclick="document.getElementById('logout-form').submit(); return false;">
                                Logout
                            </a>
                            <form id="logout-form" action="{% url 'accounts:logout' %}" method="post" style="display: none;">
                                {% csrf_token %}
                            </form>
                        </li>
                        
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        {% endif %}
        
                        <li class="nav-item">
                            <a class="nav-link" href="contact.html">Contact</a>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                         {% if user.is_authenticated and user.role == 'employer' %}
                            <a href="#"> 
                             
                              <img src={{ profile.logo.url }} alt="Company Logo" height="40"/>
                            </a>
                          {% else %}
                          <a href="#">
                            <img src="" alt="" height="40"/>
                          </a>

                          {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </nav>
        


        {% block body %}
        {% endblock %}
        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Company</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
                            
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                            </br>Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<!-- Footer End -->

        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'core/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'core/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'core/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'core/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'core/js/main.js' %}"></script>
</body>

</html>