jobportal/company_panel/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_view



app_name = 'company_panel'

urlpatterns = [    

    # Employer-only section (matches /company/ pattern)
    path('company/panel/', views.company_panel, name='company_panel'),
    path('company/panel/edit/<int:pk>/', views.edit_job_offer, name='edit_job_offer'),
    path('company/panel/create/', views.create_job_offer, name='create_job_offer'),

]

jobportal/core/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_view



urlpatterns = [
    path('', views.index, name='index'),    
   
]

jobportal/jobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('external_api.urls')),
    path('', include('accounts.urls')), 
    path('', include('company_panel.urls')),
    path('', include('applications.urls')),
    path('', include('jobboard.urls'))

] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / "static")

jobportal/company_panel/models.py
from django.db import models
from ckeditor.fields import RichTextField 
from accounts.models import User 
from ckeditor.fields import RichTextField 

JOB_TYPE_CHOICES = [
    ('full-time', 'Full Time'),
    ('part-time', 'Part Time'),
    ('internship', 'Internship'),
]

JOB_PLACE_CHOICES = [
    ('remote', 'Remote'),
    ('on-site', 'On Site'),
    ('hybrid', 'Hybrid'),
]

class JobOffers(models.Model): 
    company = models.ForeignKey(User,on_delete=models.CASCADE, limit_choices_to={'role': 'employer'}, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True) 
    description = RichTextField() 
    location = models.CharField(max_length=255, blank=True, null=True)
    salary = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    published = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    jobtype = models.CharField(
        max_length=20, 
        choices=JOB_TYPE_CHOICES, 
        default='full-time', 
        blank=True
    )
    jobplace = models.CharField(
        max_length=20, 
        choices=JOB_PLACE_CHOICES, 
        default='on-site', 
        blank=True
    )
    
    
    def __str__(self):
        return self.title

jobportal/company_panel/forms.py
from  django import forms
from .models import JobOffers
from ckeditor.widgets import CKEditorWidget 
from django.utils.translation import gettext_lazy as _
 


class JobOffersForm(forms.ModelForm): 
    description = forms.CharField(widget=CKEditorWidget(config_name='full'), label=_('Content')) 
    
    class Meta: 
        model = JobOffers
        fields = '__all__'

jobportal/company_panel/views.py
from django.shortcuts import render, redirect 
from .forms import JobOffersForm
from .models import JobOffers
from django.core.paginator import Paginator

# Create your views here.


def company_panel(request): 
    
    joboffers = JobOffers.objects.filter(company=request.user) 
    
    paginator = Paginator(joboffers, 10)  # Show 25 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    return render(request,'company_panel/company_panel.html', {'page_obj': page_obj}) 

def create_job_offer(request):
    if request.method == 'POST':
        form = JobOffersForm(request.POST, request.FILES)
        if form.is_valid():
            job_offer = form.save(commit=False)
            job_offer.company = request.user
            job_offer.save()
            return redirect('company_panel:company_panel')
    else:
        form = JobOffersForm()
    return render(request, 'company_panel/edit_job_offers.html', {'job_offers_form': form})


def edit_job_offer(request, pk):
    job_offer = JobOffers.objects.get(pk=pk)

    if request.method == 'POST':
        form = JobOffersForm(request.POST, request.FILES, instance=job_offer)
        if form.is_valid():
            form.save()
            return redirect('company_panel:company_panel')
    else:
        form = JobOffersForm(instance=job_offer)

    return render(request, 'company_panel/edit_job_offers.html', {'job_offers_form': form})

jobportal/company_panel/templates/company_panel/company_panel.html
{% extends 'core/base.html' %}
{% load static %}
{% block body %}
{% load tz %}
{% load widget_tweaks %}


<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include "company_panel/sidebar.html" %}
        <div class="col py-3">
           
            <h1>Hello from control Panel</h1>
      

            {% for job_offers in page_obj %}


                {# Each "contact" is a Contact model object. #}
                <h5>{{ job_offers.title|upper }}</h5>
                <p>{{  job_offers.description|safe | truncatewords:20 }} </p>
                <p>{{ job_offers.location }}</p>
                <p>{{ job_offers.published }}</p>
                <a href="{% url 'company_panel:edit_job_offer' job_offers.id %}">View Details</a>


            
            {% endfor %}

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>

            <div class="container mt-3"></div>
				<h2>Pagination</h2>
				<p>To create a basic pagination, add the .pagination class to an ul element. Then add the .page-item to each li element and a .page-link class to each link inside li:</p>                  
				<ul class="pagination">
                    {% if page_obj.has_previous %}
				         <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                         <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">PREVIOUS</a></li>
                    {% endif %}
				  <li class="current page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                  {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">NEXT</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">LAST</a></li>
                  {% endif %}
				</ul>
			  </div>
        </div>
    </div>
</div>


{% endblock %}

jobportal/company_panel/templates/company_panel/edit_job_offers.html
{% extends 'core/base.html' %}
{% load static %}
{% block body %}
{% load tz %}
{% load widget_tweaks %}


<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include "company_panel/sidebar.html" %}
        <div class="col py-3">
           
            <h1>Hello from JOB OFFER</h1>
            <form method="POST">
                {% csrf_token %}
                {{ job_offers_form.media }}
                {{ job_offers_form.as_p }}
                <button type="submit" >Submit </button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

jobportal/company_panel/templates/company_panel/sidebar.html
<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <span class="fs-5 d-none d-sm-inline">Menu</span>
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
                <a href="{% url 'company_panel:company_panel' %}" class="nav-link align-middle px-0">
                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                </a>
            </li>
            <li>
                <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
                <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                    <li class="w-100">
                        <a href="{% url 'company_panel:create_job_offer' %}" class="nav-link px-0"> <span class="d-none d-sm-inline">Create/Edit Job Offer</span>  </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
            </li>
            <li>
                <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                    <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>
                <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                    <li class="w-100">
                        <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
                    <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                    <li class="w-100">
                        <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>
            </li>
        </ul>
        <hr>
        <div class="dropdown pb-4">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                <span class="d-none d-sm-inline mx-1">loser</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                <li><a class="dropdown-item" href="#">New project...</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Sign out</a></li>
            </ul>
        </div>
    </div>
</div>